<!doctype html>
<html lang="en" class="no-js">
		<head>
				<meta charset="UTF-8">
				<meta name="viewport" content="width=device-width, initial-scale=1">
				<link rel='stylesheet' href='/<?php echo SITEURL; ?>assets/css/font.css'  type='text/css'>
				<link rel="stylesheet" href="/<?php echo SITEURL; ?>assets/css/style.css"> <!-- css style -->
				<link rel="stylesheet" href="/<?php echo SITEURL; ?>assets/css/table.css"> <!-- css table -->
				<link rel="stylesheet" href="/<?php echo SITEURL; ?>assets/css/reset.css"> <!-- css reset -->
				<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script><!-- JS jquery -->
				<script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script><!-- JS jquery ui -->
		    <script src="https://code.highcharts.com/highcharts.js"></script>
		    <script src="https://code.highcharts.com/modules/exporting.js"></script>
				<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
				<script src="/<?php echo SITEURL; ?>assets/js/main.js"></script>
				<title>Finite Element Methods - U of T</title>
		</head>
		<body>
