<?php

/**
 * SITEURL
 */
define('SITEURL', '2dtrussdeflection/');

/**
 * Young modulus
 * assumed same to all members
 */
define('E', '29000');

/**
 * magnifying factor of displacements
 */
define('MAGNIFICATION_FACTOR', 5.0);

/**
 * length amplification factor for unit conversion
 */
define('LENGTH_FACTOR', 12.0);

/**
 * magnifying factor in general
 */
define('GENERAL_MAGNIFICATION_FACTOR', 1.5);

?>
